version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  lint_app:
    resource_class: small
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint App
      - when:
          condition:
            or:
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - persist_to_workspace:
                root: ~/project
                paths:
                  - .
  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
workflows:
  vaunch:
    jobs:
      - lint_app
      - deploy:
          requires:
            - lint_app # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on master