version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_app:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm build
          name: Build app
      - persist_to_workspace:
          root: ~/dist
          paths:
            - .
workflows:
  vaunch:
    jobs:
      - build_app
